<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Formulario de ingreso · KM314</title>
    <style>
        *{box-sizing:border-box}body{margin:0;background:#f3f7f5;color:#17251f;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}.wrap{max-width:980px;margin:0 auto;padding:28px 18px 70px}.hero{background:linear-gradient(125deg,#123f35,#18765a);border-radius:22px;padding:27px;color:#fff;box-shadow:0 15px 35px #123d3028}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#b7ead7}.hero h1{margin:6px 0 5px;font-size:28px}.hero p{margin:0;color:#d6eee5}.fixed{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:20px}.fixed div{background:#ffffff16;border:1px solid #ffffff2c;border-radius:12px;padding:11px}.fixed span{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#b7d6cb}.fixed b{display:block;margin-top:3px;font-size:14px}.card{background:#fff;border:1px solid #dbe7e2;border-radius:18px;padding:22px;margin-top:16px;box-shadow:0 5px 18px #173d3010}.card h2{font-size:18px;margin:0 0 4px}.hint{font-size:12px;color:#6d7d76;margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid.four{grid-template-columns:repeat(4,1fr)}label{font-size:12px;font-weight:750;color:#4f625a;display:block}input,textarea{width:100%;border:1px solid #cddbd5;border-radius:10px;padding:11px 12px;margin-top:5px;background:#fff;color:#17251f;font:inherit}input:focus,textarea:focus{outline:2px solid #62b99a55;border-color:#298365}.person,.vehicle,.pet,.extra{background:#f6f9f8;border:1px solid #dfe9e5;border-radius:14px;padding:16px;margin-top:12px}.row-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.row-head b{font-size:14px}.remove{border:0;background:#feecec;color:#a52e2e;border-radius:8px;padding:6px 9px;cursor:pointer}.add{border:1px dashed #53a889;background:#eff9f5;color:#176b53;border-radius:10px;padding:10px 14px;font-weight:750;cursor:pointer;margin-top:12px}.docs{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:13px}.doc{background:#fff;border:1px solid #dfebe6;border-radius:10px;padding:10px}.doc b{font-size:11px}.checks{display:flex;gap:18px;flex-wrap:wrap;margin-top:13px}.checks label{display:flex;align-items:center;gap:7px}.checks input{width:auto;margin:0}.submit{width:100%;border:0;background:#176b53;color:#fff;border-radius:12px;padding:14px;font-size:15px;font-weight:800;cursor:pointer;margin-top:17px}.errors{background:#fff0f0;color:#992e2e;border:1px solid #f3caca;border-radius:14px;padding:14px 18px;margin-top:16px}.state{text-align:center;background:#fff;border-radius:20px;padding:50px 25px;margin-top:18px;border:1px solid #dbe7e2}.state .icon{font-size:42px}.state h2{margin:10px}.terms{display:flex;align-items:flex-start;gap:10px;margin-top:16px}.terms input{width:auto;margin-top:3px}.terms a{color:#176b53}@media(max-width:700px){.fixed,.grid.four{grid-template-columns:repeat(2,1fr)}.grid,.docs{grid-template-columns:1fr}.hero h1{font-size:23px}}
    </style>
</head>
<body><main class="wrap">
    <header class="hero"><span class="eyebrow">KM314 · Invitación segura</span><h1>Formulario de ingreso</h1><p>Complete los datos solicitados para que el propietario pueda revisar la solicitud.</p>
        <div class="fixed"><div><span>Propietario</span><b>{{ $invitation->owner->nombres() }}</b></div><div><span>Acceso</span><b>Lote</b></div><div><span>Lote</span><b>{{ $invitation->lote->getNombre() }}</b></div><div><span>Tipo de ingreso</span><b>Inquilino</b></div></div>
    </header>
    @if(session('submitted') || $invitation->used_at)
        <section class="state"><div class="icon">✓</div><h2>Formulario enviado</h2><p>El propietario fue notificado y deberá aprobarlo antes de que pase a revisión de administración.</p></section>
    @elseif(!$invitation->isAvailable())
        <section class="state"><div class="icon">⌛</div><h2>Este enlace ya no está disponible</h2><p>Venció o fue cancelado. Solicite al propietario un enlace nuevo.</p></section>
    @else
        @if($errors->any())<div class="errors"><b>Revise los siguientes datos:</b><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ route('form-control-public.store',$token) }}" enctype="multipart/form-data">@csrf
            <section class="card"><h2>Fecha y horario</h2><p class="hint">Indique el período durante el cual se permitirá el ingreso.</p><div class="grid four">
                <label>Fecha desde<input type="date" name="start_date" min="{{ now()->format('Y-m-d') }}" value="{{ old('start_date') }}" required></label><label>Hora desde<input type="time" name="start_time" value="{{ old('start_time') }}" required></label>
                <label>Fecha hasta<input type="date" name="end_date" min="{{ now()->format('Y-m-d') }}" value="{{ old('end_date') }}" required></label><label>Hora hasta<input type="time" name="end_time" value="{{ old('end_time') }}" required></label>
            </div></section>
            <section class="card"><h2>Personas</h2><p class="hint">Cargue todas las personas que ingresarán al barrio.</p><div id="people"></div><button class="add" type="button" onclick="addPerson()">+ Agregar persona</button></section>
            <section class="card"><h2>Vehículos</h2><p class="hint">Opcional. Si agrega un vehículo, complete todos sus datos.</p><div id="vehicles"></div><button class="add" type="button" onclick="addVehicle()">+ Agregar vehículo</button></section>
            <section class="card"><h2>Información adicional</h2><div id="extras"></div><button class="add" type="button" onclick="addExtra()">+ Agregar documento</button><div id="pets"></div><button class="add" type="button" onclick="addPet()">+ Agregar mascota</button><label style="margin-top:16px">Observaciones<textarea name="observations" rows="4">{{ old('observations') }}</textarea></label></section>
            <section class="card"><label class="terms"><input type="checkbox" name="accept_terms" value="1" required><span>He leído y acepto los <a href="{{ route('terminos-y-condiciones',['id'=>1]) }}" target="_blank">términos y condiciones</a>.</span></label><button class="submit" type="submit">Enviar al propietario para aprobación</button></section>
        </form>
        <template id="person-template"><div class="person"><div class="row-head"><b>Persona</b><button type="button" class="remove" onclick="removeRow(this)">Quitar</button></div><div class="grid four"><label>DNI<input name="people[__I__][dni]" inputmode="numeric" required></label><label>Nombre<input name="people[__I__][first_name]" required></label><label>Apellido<input name="people[__I__][last_name]" required></label><label>Teléfono<input name="people[__I__][phone]" inputmode="numeric" maxlength="15"></label></div><div class="checks"><label><input type="checkbox" name="people[__I__][is_responsable]" value="1"> Responsable</label><label><input type="checkbox" name="people[__I__][is_acompanante]" value="1"> Acompañante</label><label><input type="checkbox" name="people[__I__][is_menor]" value="1"> Menor</label></div><div class="docs">@foreach($personDocuments as $j=>$doc)<div class="doc"><b>{{ $doc['name'] }}{{ $doc['required']?' *':'' }}</b><input type="hidden" name="people[__I__][documents][{{ $j }}][name]" value="{{ $doc['name'] }}"><input type="file" name="people[__I__][documents][{{ $j }}][file]" accept="image/*,.pdf" {{ $doc['required']?'required':'' }}>@if($doc['date_required'])<label>Vencimiento<input type="date" name="people[__I__][documents][{{ $j }}][expires_at]" required></label>@endif</div>@endforeach</div></div></template>
        <template id="vehicle-template"><div class="vehicle"><div class="row-head"><b>Vehículo</b><button type="button" class="remove" onclick="removeRow(this)">Quitar</button></div><div class="grid four"><label>Marca<input name="vehicles[__I__][marca]" required></label><label>Modelo<input name="vehicles[__I__][modelo]" required></label><label>Patente<input name="vehicles[__I__][patente]" required></label><label>Color<input name="vehicles[__I__][color]" required></label></div><div class="docs">@foreach($vehicleDocuments as $j=>$doc)<div class="doc"><b>{{ $doc['name'] }}{{ $doc['required']?' *':'' }}</b><input type="hidden" name="vehicles[__I__][documents][{{ $j }}][name]" value="{{ $doc['name'] }}"><input type="file" name="vehicles[__I__][documents][{{ $j }}][file]" accept="image/*,.pdf" {{ $doc['required']?'required':'' }}>@if($doc['date_required'])<label>Vencimiento<input type="date" name="vehicles[__I__][documents][{{ $j }}][expires_at]" required></label>@endif</div>@endforeach</div></div></template>
        <template id="extra-template"><div class="extra"><div class="row-head"><b>Documento adicional</b><button type="button" class="remove" onclick="removeRow(this)">Quitar</button></div><div class="grid"><label>Descripción<input name="extra_documents[__I__][description]"></label><label>Archivo<input type="file" name="extra_documents[__I__][file]" accept="image/*,.pdf" required></label></div></div></template>
        <template id="pet-template"><div class="pet"><div class="row-head"><b>Mascota</b><button type="button" class="remove" onclick="removeRow(this)">Quitar</button></div><div class="grid four"><label>Tipo<input name="pets[__I__][type]"></label><label>Raza<input name="pets[__I__][breed]"></label><label>Nombre<input name="pets[__I__][name]"></label><label class="terms"><input type="checkbox" name="pets[__I__][vaccinated]" value="1"> Vacunada</label></div></div></template>
        <script>
            let counters={person:0,vehicle:0,extra:0,pet:0};
            function oldValue(data,name){const keys=[...name.matchAll(/\[([^\]]+)\]/g)].map(match=>match[1]).slice(1);let value=data;for(const key of keys){if(value===undefined||value===null)return undefined;value=value[key]}return value}
            function add(kind,target,data={}){const i=counters[kind]++;const container=document.getElementById(target);container.insertAdjacentHTML('beforeend',document.getElementById(kind+'-template').innerHTML.replaceAll('__I__',i));const row=container.lastElementChild;row.querySelectorAll('input,textarea').forEach(field=>{if(field.type==='file')return;const value=oldValue(data,field.name);if(value===undefined)return;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=value});}
            function addPerson(data={}){add('person','people',data)}function addVehicle(data={}){add('vehicle','vehicles',data)}function addExtra(data={}){add('extra','extras',data)}function addPet(data={}){add('pet','pets',data)}function removeRow(button){button.closest('.person,.vehicle,.extra,.pet').remove()}
            const previous={people:@json(old('people',[])),vehicles:@json(old('vehicles',[])),extras:@json(old('extra_documents',[])),pets:@json(old('pets',[]))};
            previous.people.length?previous.people.forEach(addPerson):addPerson();previous.vehicles.forEach(addVehicle);previous.extras.forEach(addExtra);previous.pets.forEach(addPet);
        </script>
    @endif
</main></body></html>
