<x-filament-panels::page>
    <div class="fcm" wire:poll.30s>@php($data=$this->monitorData)
        <header class="fcm-hero">
            <div class="fcm-hero-copy"><span>Control documental en tiempo real</span><h2>Monitor de Formularios</h2><p>Actualizado {{ $data['updated_at'] }}</p></div>
            <div class="fcm-hero-art" aria-hidden="true"><i></i><i></i><i></i></div>
            <div class="fcm-hero-actions">
                @if($data['can_create'])<a class="fcm-create" href="{{ $data['create_url'] }}"><x-heroicon-o-plus class="h-5 w-5" /> Nuevo formulario</a>@endif
                @if(auth()->user()->hasRole('owner') && $data['can_create']){{ ($this->sharePublicFormAction) }}@endif
                <a class="fcm-list" href="{{ $data['list_url'] }}">Abrir listado completo</a>
            </div>
        </header>
        <section class="fcm-stats">
            @if(auth()->user()->hasRole('owner'))<button wire:click="setStatus('OwnerPending')"><b>{{ $data['stats']['owner_pending'] }}</b><span>Esperan tu aprobación</span></button>@endif
            <button wire:click="setStatus('Pending')"><b>{{ $data['stats']['pending'] }}</b><span>Pendientes</span></button>
            <button wire:click="setStatus('Authorized')"><b>{{ $data['stats']['authorized'] }}</b><span>Autorizados</span></button>
            <button wire:click="setStatus('attention')" class="attention"><b>{{ $data['stats']['attention'] }}</b><span>Requieren atención</span><em>{{ $data['stats']['denied'] }} rechazados · {{ $data['stats']['overdue'] }} vencidos · {{ $data['stats']['expired'] }} expirados</em></button>
        </section>
        <section class="fcm-toolbar"><div class="fcm-tabs">@foreach(['active'=>'Activos','all'=>'Todos','attention'=>'Atención','OwnerPending'=>'Form. Públicos','Pending'=>'Pendientes','Authorized'=>'Autorizados','Denied'=>'Rechazados','Vencido'=>'Vencidos','Expirado'=>'Expirados'] as $key=>$label)@if($key!=='OwnerPending'||auth()->user()->hasRole('owner'))<button wire:click="setStatus('{{ $key }}')" @class(['active'=>$status===$key])>{{ $label }}</button>@endif @endforeach</div><input wire:model.live.debounce.350ms="search" placeholder="Buscar lote, propietario, tipo o número…"></section>
        <section class="fcm-grid">@forelse($data['forms'] as $form)
            <article class="fcm-card state-{{ $form['computed_status'] }}"><div class="fcm-top"><span>FORMULARIO #{{ $form['id'] }}</span><b>{{ $form['status_label'] }}</b></div>
                <div class="fcm-lot"><small>LOTE</small><h3>{{ $form['lot'] }}</h3></div><p class="fcm-owner">{{ $form['owner'] }}</p>
                <div class="fcm-meta"><div><span>Ingreso</span><strong>{{ $form['income'] }}</strong></div><div><span>Personas</span><strong>{{ $form['people'] }}</strong></div></div>
                <div class="fcm-range"><span>Vigencia</span><strong>{{ $form['range'] }}</strong></div>
                <div class="fcm-actions"><a href="{{ $form['view_url'] }}">Ver detalle</a>{{ ($this->qrAction)(['form'=>$form['id']]) }}@if($form['can_edit'])<a class="edit" href="{{ $form['edit_url'] }}">Editar</a>@endif @if($form['can_owner_approve']){{ ($this->ownerApproveAction)(['form'=>$form['id']]) }}@endif @if($form['can_admin_approve']){{ ($this->adminApproveAction)(['form'=>$form['id']]) }}@endif @if($form['can_reject']){{ ($this->rejectAction)(['form'=>$form['id']]) }}@endif @if($form['can_delete']){{ ($this->deleteFormAction)(['form'=>$form['id']]) }}@endif</div>
            </article>
        @empty<div class="fcm-empty"><span>◇</span><h3>No hay formularios para mostrar</h3><p>Pruebe otro estado o cambie la búsqueda.</p></div>@endforelse</section>
    </div>
    <style>
        .fcm{--ink:#201a32;--muted:#716a80;--line:#e2ddec;color:var(--ink)}.dark .fcm{--ink:#f3efff;--muted:#b8afca;--line:#443b59;color:var(--ink)}
        .fcm-hero{position:relative;overflow:hidden;display:flex;justify-content:space-between;align-items:center;gap:22px;padding:28px 30px;border-radius:22px;color:white;background:linear-gradient(125deg,#31215f,#6446a7 62%,#9a5fc3);box-shadow:0 16px 40px #3d28672c}.fcm-hero-copy,.fcm-hero-actions{position:relative;z-index:2}.fcm-hero span{text-transform:uppercase;letter-spacing:.13em;font-size:11px;font-weight:800;color:#ddd0ff}.fcm-hero h2{font-size:28px;font-weight:850;margin:4px 0}.fcm-hero p{font-size:12px;color:#ddd4ec}.fcm-hero-actions{display:flex;align-items:center;justify-content:flex-end;gap:9px;flex-wrap:wrap;max-width:570px}.fcm-hero-actions>a{display:inline-flex;align-items:center;gap:7px;padding:10px 14px;border-radius:11px;font-size:12px;font-weight:800}.fcm-create{background:#fff;color:#4b3186;box-shadow:0 5px 18px #24124945}.fcm-list{color:#fff;border:1px solid #ffffff65;background:#ffffff12}.fcm-hero-art{position:absolute;z-index:1;right:42%;top:9px;width:132px;height:105px;opacity:.17;transform:rotate(-7deg)}.fcm-hero-art i{position:absolute;width:72px;height:88px;border:2px solid #fff;border-radius:9px;background:#ffffff0d;box-shadow:0 9px 18px #24124933}.fcm-hero-art i:after{content:'';position:absolute;left:13px;right:13px;top:21px;height:2px;background:#fff;box-shadow:0 13px 0 #fff,0 26px 0 #fff}.fcm-hero-art i:nth-child(1){left:4px;top:10px}.fcm-hero-art i:nth-child(2){left:28px;top:3px}.fcm-hero-art i:nth-child(3){left:53px;top:-3px}
        .fcm-stats{display:flex;gap:14px;margin:18px 0}.fcm-stats button{flex:1;text-align:left;padding:17px 19px;background:white;border:1px solid var(--line);border-radius:16px;color:var(--ink)}.dark .fcm-stats button,.dark .fcm-toolbar,.dark .fcm-card{background:#211b2e}.fcm-stats b{display:block;font-size:27px;color:#7654b8}.dark .fcm-stats b{color:#b99bec}.fcm-stats span{display:block;font-size:12px;color:var(--muted);font-weight:700}.fcm-stats em{display:block;margin-top:4px;font-size:10px;font-style:normal;color:var(--muted);font-weight:600}.fcm-stats .attention b{color:#d27928}
        .fcm-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px;background:#fff;border:1px solid var(--line);border-radius:15px}.fcm-tabs{display:flex;gap:3px;flex-wrap:wrap}.fcm-tabs button{font-size:11px;font-weight:750;color:var(--muted);padding:8px 10px;border-radius:8px}.fcm-tabs button.active{background:#eee8fa;color:#543494}.dark .fcm-tabs button.active{background:#e8ddff;color:#4d2e87}.fcm-toolbar input{width:310px;padding:9px 11px;border:1px solid var(--line);border-radius:9px;background:transparent;color:var(--ink)}
        .fcm-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-top:16px}.fcm-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;position:relative;overflow:hidden;transition:.18s}.fcm-card:before{content:'';position:absolute;inset:0 auto 0 0;width:4px;background:#8c6bc2}.fcm-card:hover{transform:translateY(-3px);box-shadow:0 12px 28px #39275d20}.fcm-card.state-Authorized:before{background:#29936d}.fcm-card.state-Denied:before,.fcm-card.state-Expirado:before{background:#d44949}.fcm-card.state-Vencido:before{background:#dd852d}.fcm-top{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.fcm-top>span{font-size:10px;letter-spacing:.1em;font-weight:850;color:var(--muted)}.fcm-top b{font-size:10px;background:#eee8fa;color:#563795;border-radius:999px;padding:5px 8px}.state-Authorized .fcm-top b{background:#e0f5ec;color:#176c50}.state-Denied .fcm-top b,.state-Expirado .fcm-top b{background:#fde8e8;color:#a53030}.state-Vencido .fcm-top b{background:#fff0dd;color:#985710}
        .fcm-lot{margin:18px 0 2px}.fcm-lot small{font-size:10px;letter-spacing:.16em;font-weight:850;color:#8b7ba7}.fcm-lot h3{font-size:30px;line-height:1;font-weight:900;color:var(--ink);margin:4px 0}.fcm-owner{font-size:13px;color:var(--muted)}.fcm-meta{display:grid;grid-template-columns:2fr 1fr;gap:8px;margin-top:15px}.fcm-meta div,.fcm-range{background:#f7f4fb;border-radius:10px;padding:9px 11px}.dark .fcm-meta div,.dark .fcm-range{background:#17131f;border:1px solid #382f4b}.fcm-meta span,.fcm-range span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.fcm-meta strong,.fcm-range strong{font-size:12px;color:var(--ink)}.fcm-range{margin-top:8px}.fcm-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-top:15px}.fcm-actions>a{font-size:12px;font-weight:800;color:#6844a3}.dark .fcm-actions>a{color:#c0a3ef}.fcm-actions .edit{border-left:1px solid var(--line);padding-left:9px}.fcm-empty{grid-column:1/-1;text-align:center;padding:60px;color:var(--muted)}.fcm-empty>span{font-size:38px;color:#9573ca}.fcm-empty h3{color:var(--ink);margin:8px;font-weight:850}
        @media(max-width:1050px){.fcm-grid{grid-template-columns:repeat(2,1fr)}.fcm-toolbar{align-items:stretch;flex-direction:column}.fcm-toolbar input{width:100%}.fcm-hero-art{right:34%}}@media(max-width:650px){.fcm-hero{align-items:flex-start;flex-direction:column;gap:17px}.fcm-hero h2{font-size:23px}.fcm-hero-actions{justify-content:flex-start}.fcm-hero-art{right:-18px;top:4px}.fcm-stats{display:grid;grid-template-columns:repeat(2,1fr)}.fcm-grid{grid-template-columns:1fr}}
        .fcm-hero-actions span{text-transform:none;letter-spacing:normal;font-size:inherit;font-weight:inherit;color:inherit}
    </style>
</x-filament-panels::page>
