<x-filament-panels::page>
    <div class="srm" wire:poll.30s>@php($data = $this->monitorData)
        <header class="srm-hero">
            <div class="srm-copy"><span>Gestión operativa en tiempo real</span><h2>Monitor de Solicitudes</h2><p>Actualizado {{ $data['updated_at'] }}</p></div>
            <div class="srm-art" aria-hidden="true"><i></i><i></i><i></i></div>
            <div class="srm-hero-actions">
                @if($data['can_create'])<a class="srm-create" href="{{ $data['create_url'] }}"><x-heroicon-o-plus class="h-5 w-5" /> Nueva solicitud</a>@endif
                @if($data['can_manage'])<a class="srm-list" href="{{ $data['list_url'] }}">Abrir listado completo</a>@endif
            </div>
        </header>

        <section class="srm-stats">
            <button wire:click="setStatus('all')" @class(['selected' => $status === 'all'])><b>{{ $data['stats']['total'] }}</b><span>Total del mes</span></button>
            <button wire:click="setStatus('active')" @class(['active', 'selected' => $status === 'active'])><b>{{ $data['stats']['active'] }}</b><span>Activas</span><em>Pendientes y en proceso</em></button>
            <button wire:click="setStatus('unassigned')" @class(['unassigned', 'selected' => $status === 'unassigned'])><b>{{ $data['stats']['unassigned'] }}</b><span>Sin asignar</span><em>Activas que necesitan responsable</em></button>
            <button wire:click="setStatus('closed')" @class(['closed', 'selected' => $status === 'closed'])><b>{{ $data['stats']['closed'] }}</b><span>Cerradas</span><em>Finalizadas, rechazadas o canceladas</em></button>
        </section>

        <section class="srm-toolbar">
            <div class="srm-tabs"><button wire:click="setStatus('all')" @class(['active' => $status === 'all'])>Todas <em>{{ $data['stats']['total'] }}</em></button>@foreach($data['status_filters'] as $filter)<button wire:click="setStatus('{{ $filter['code'] }}')" @class(['active' => $status === $filter['code']])><i style="--status-color: {{ $filter['color'] ?: '#66808c' }}"></i>{{ $filter['name'] }} <em>{{ $filter['count'] }}</em></button>@endforeach</div>
            <div class="srm-filters"><label><span>Mes</span><input type="month" wire:model.live="month"></label><input wire:model.live.debounce.350ms="search" placeholder="Buscar solicitud, lote, propietario o servicio…"></div>
        </section>

        <section class="srm-grid">@forelse($data['requests'] as $request)
            <article class="srm-card state-{{ $request['status_code'] }}">
                <div class="srm-top"><span>SOLICITUD #{{ $request['id'] }}</span><b>{{ $request['status'] }}</b></div>
                <div class="srm-lot"><small>LOTE</small><h3>{{ $request['lot'] }}</h3></div>
                <p class="srm-title">{{ $request['title'] }}</p><p class="srm-owner">{{ $request['owner'] }}</p>
                <div class="srm-meta"><div><span>Servicio</span><strong>{{ $request['service'] }}</strong></div><div><span>Programada</span><strong>{{ $request['scheduled'] }}</strong></div></div>
                @if($request['assigned'])<p class="srm-assigned">Asignada a {{ $request['assigned'] }}</p>@endif
                <div class="srm-actions"><a href="{{ $request['url'] }}">Ver detalle</a>@if($request['can_edit'])<a class="edit" href="{{ $request['url'] }}">Editar</a>@endif @if($request['can_change_status']){{ ($this->changeStatusAction)(['request' => $request['id']]) }}@endif</div>
            </article>
        @empty
            <div class="srm-empty"><span>◇</span><h3>No hay solicitudes para mostrar</h3><p>Probá otro estado, mes o búsqueda.</p></div>
        @endforelse</section>
    </div>
    <style>
        .srm{--ink:#172d39;--muted:#66808c;--line:#d7e4e8;color:var(--ink)}.dark .srm{--ink:#eaf8fb;--muted:#a7c2c9;--line:#304c55;color:var(--ink)}
        .srm-hero{position:relative;overflow:hidden;display:flex;justify-content:space-between;align-items:center;gap:22px;padding:28px 30px;border-radius:22px;color:#fff;background:linear-gradient(125deg,#0e4b62,#12758b 61%,#1ca4a0);box-shadow:0 16px 40px #0b62732b}.srm-copy,.srm-hero-actions{position:relative;z-index:2}.srm-copy>span{text-transform:uppercase;letter-spacing:.13em;font-size:11px;font-weight:800;color:#b8eff0}.srm-copy h2{font-size:28px;font-weight:850;margin:4px 0}.srm-copy p{font-size:12px;color:#c6e8eb}.srm-hero-actions{display:flex;align-items:center;justify-content:flex-end;gap:9px;flex-wrap:wrap}.srm-hero-actions a{display:inline-flex;align-items:center;gap:7px;padding:10px 14px;border-radius:11px;font-size:12px;font-weight:800}.srm-create{background:#fff;color:#0c5d70;box-shadow:0 5px 18px #063b4d52}.srm-list{color:#fff;border:1px solid #ffffff65;background:#ffffff12}.srm-art{position:absolute;right:39%;top:8px;width:130px;height:105px;opacity:.18;transform:rotate(-7deg)}.srm-art i{position:absolute;width:70px;height:84px;border:2px solid #fff;border-radius:11px;background:#ffffff0d;box-shadow:0 9px 18px #063b4d33}.srm-art i:after{content:'';position:absolute;left:13px;right:13px;top:20px;height:2px;background:#fff;box-shadow:0 13px 0 #fff,0 26px 0 #fff}.srm-art i:nth-child(1){left:4px;top:10px}.srm-art i:nth-child(2){left:29px;top:3px}.srm-art i:nth-child(3){left:54px;top:-4px}
        .srm-stats{display:flex;gap:14px;margin:18px 0}.srm-stats button{flex:1;text-align:left;padding:17px 19px;background:#fff;border:1px solid var(--line);border-radius:16px;color:var(--ink)}.dark .srm-stats button,.dark .srm-toolbar,.dark .srm-card{background:#14242a}.srm-stats button.selected{outline:2px solid #16859a;outline-offset:1px}.srm-stats b{display:block;font-size:27px;color:#148198}.srm-stats span{display:block;font-size:12px;color:var(--muted);font-weight:700}.srm-stats em{display:block;margin-top:4px;font-size:10px;font-style:normal;color:var(--muted);font-weight:600}.srm-stats .unassigned b{color:#d87826}.srm-stats .closed b{color:#66737b}
        .srm-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px;background:#fff;border:1px solid var(--line);border-radius:15px}.srm-tabs{display:flex;gap:3px;flex-wrap:wrap}.srm-tabs button{display:inline-flex;align-items:center;gap:6px;font-size:11px;font-weight:750;color:var(--muted);padding:8px 10px;border-radius:8px}.srm-tabs button i{width:7px;height:7px;border-radius:999px;background:var(--status-color);display:inline-block}.srm-tabs button em{font-size:10px;font-style:normal;color:inherit;opacity:.72}.srm-tabs button.active{background:#dff2f4;color:#096278}.dark .srm-tabs button.active{background:#cceff1;color:#07576a}.srm-filters{display:flex;align-items:flex-end;gap:8px}.srm-filters label span{display:block;margin:0 0 3px 2px;font-size:9px;text-transform:uppercase;letter-spacing:.1em;font-weight:800;color:var(--muted)}.srm-toolbar input{padding:9px 11px;border:1px solid var(--line);border-radius:9px;background:transparent;color:var(--ink)}.srm-filters input[type=month]{width:145px}.srm-filters>input{width:310px}
        .srm-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-top:16px}.srm-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;position:relative;overflow:hidden;transition:.18s}.srm-card:before{content:'';position:absolute;inset:0 auto 0 0;width:4px;background:#16859a}.srm-card:hover{transform:translateY(-3px);box-shadow:0 12px 28px #12607220}.srm-card.state-completed:before{background:#29936d}.srm-card.state-rejected:before{background:#d44949}.srm-card.state-cancelled:before{background:#7b8790}.srm-top{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.srm-top>span{font-size:10px;letter-spacing:.1em;font-weight:850;color:var(--muted)}.srm-top b{font-size:10px;background:#dff2f4;color:#096278;border-radius:999px;padding:5px 8px}.state-completed .srm-top b{background:#e0f5ec;color:#176c50}.state-rejected .srm-top b{background:#fde8e8;color:#a53030}.state-cancelled .srm-top b{background:#e8ecee;color:#53616a}.srm-lot{margin:18px 0 2px}.srm-lot small{font-size:10px;letter-spacing:.16em;font-weight:850;color:#408e9b}.srm-lot h3{font-size:30px;line-height:1;font-weight:900;color:var(--ink);margin:4px 0}.srm-title{font-size:15px;font-weight:800;margin:11px 0 2px}.srm-owner,.srm-assigned{font-size:12px;color:var(--muted)}.srm-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:15px}.srm-meta div{background:#f2f8f9;border-radius:10px;padding:9px 11px}.dark .srm-meta div{background:#0d181c;border:1px solid #29434b}.srm-meta span{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.srm-meta strong{font-size:11px;color:var(--ink)}.srm-assigned{margin:9px 0 0}.srm-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-top:15px}.srm-actions>a{font-size:12px;font-weight:800;color:#08738b}.dark .srm-actions>a{color:#7ee0e4}.srm-actions .edit{border-left:1px solid var(--line);padding-left:9px}.srm-empty{grid-column:1/-1;text-align:center;padding:60px;color:var(--muted)}.srm-empty>span{font-size:38px;color:#2997aa}.srm-empty h3{color:var(--ink);margin:8px;font-weight:850}
        @media(max-width:1050px){.srm-grid{grid-template-columns:repeat(2,1fr)}.srm-toolbar{align-items:stretch;flex-direction:column}.srm-filters{align-items:flex-end}.srm-filters>input{flex:1;width:auto}.srm-art{right:34%}}@media(max-width:650px){.srm-hero{align-items:flex-start;flex-direction:column;gap:17px}.srm-copy h2{font-size:23px}.srm-hero-actions{justify-content:flex-start}.srm-art{right:-18px;top:4px}.srm-stats{display:grid;grid-template-columns:repeat(2,1fr)}.srm-grid{grid-template-columns:1fr}.srm-filters{align-items:stretch;flex-direction:column}.srm-filters input[type=month],.srm-filters>input{width:100%}}
    </style>
</x-filament-panels::page>
